Elao/elao_

.env
.github/workflows/build_pr.yaml
assets/scss/components/_brick-contribute.scss
assets/scss/style.scss
config/routes.yaml
config/routes/external/github.yaml
config/services.yaml
src/Model/Article.php
src/Router/ExternalUrlGenerator.php
src/Stenope/Processor/GithubEditLinkProcessor.php
src/Twig/Extension/ExternalUrlExtension.php
templates/blog/article.html.twig

Fixes #303
Lien mis pour l'exemple en bas d'article. A voir comment on choisi de l'intégrer :)
(si je me suis pas foiré sur le workflow, l'URL d'édition devrait même correspondre à la PR en cours. EDIT: loupé, conflit d'env vars avec Github Actions)
**NOTE: on attend de passer le repo en public pour merge**

[Blog] Add a Github edit link to articles

---

config/packages/stenope.yaml
public/.well-known/security.txt

Add .well-known/security.txt

---

assets/scss/components/_article-author.scss
content/blog/styleguide/example.md
templates/blog/article.html.twig
templates/blog/index.html.twig

[Blog] Link authors

---

README.md
assets/scss/generic/_kbd.scss
assets/scss/style.scss
content/blog/styleguide/example.md

https://elao.github.io/elao_/pr/331/blog/styleguide/example/
TODO :

Add typo rules to example.md

---

assets/scss/components/_article-footer.scss
assets/scss/components/_brick.scss

Fixes https://github.com/Elao/elao_/issues/315

[Blog] Fix bricks margins

---

assets/scss/components/_banner-case-study.scss
assets/scss/components/_banner-home.scss
assets/scss/components/_banner-methodology.scss
assets/scss/components/_banner-services.scss
assets/scss/components/_banner-team.scss
assets/scss/components/_banner-values.scss
assets/scss/components/_banner.scss
assets/scss/components/_breadcrumb.scss
assets/scss/components/_contact.scss
assets/scss/components/_header.scss
assets/scss/components/_nav-mobile.scss
assets/scss/components/_titles.scss
assets/scss/pages/_page-contact.scss
assets/scss/pages/_page-services.scss
templates/site/contact.html.twig
templates/site/home.html.twig
templates/site/methodology.html.twig
templates/site/services.html.twig

Preview : https://elao.github.io/elao_/pr/345/
Next :

Better banners

---

templates/base.html.twig
templates/footer.html.twig
templates/site/home.html.twig
translations/messages+intl-icu.fr.yaml

Fixes https://elao.slack.com/archives/CQ6L47QUB/p1622629914003500

Fix job offer(s) pluralization + move footer in dedicated template

---

assets/scss/components/_btn.scss
templates/blog/index.html.twig
templates/case_study/index.html.twig
templates/case_study/show.html.twig
templates/job/index.html.twig
templates/partials/svg-arrow.html.twig
templates/site/contact.html.twig
templates/site/home.html.twig
templates/site/services.html.twig
templates/site/values.html.twig
templates/team/index.html.twig

Fixes https://github.com/Elao/elao_/issues/330

Better buttons

---

Makefile
composer.json
composer.lock
config/packages/stenope.yaml
src/Stenope/Processor/AssetsProcessor.php
src/Stenope/Processor/AuthorProcessor.php
src/Stenope/Processor/CategoryProcessor.php
src/Stenope/Processor/DefaultTocProcessor.php
src/Stenope/Processor/GithubEditLinkProcessor.php
src/Stenope/Processor/HtmlAnchorProcessor.php
src/Stenope/Processor/ResizeImagesContentProcessor.php
src/Stenope/Processor/TagProcessor.php

https://github.com/StenopePHP/Stenope/pull/36

Use Stenope shared HTML crawlers feature

---

config/packages/translation.yaml

| before | after |
| - | - |
| ![Capture d’écran 2021-06-18 à 14 55 56](https://user-images.githubusercontent.com/2211145/122564171-560dd500-d045-11eb-973d-070634683869.png) | ![Capture d’écran 2021-06-18 à 14 55 46](https://user-images.githubusercontent.com/2211145/122564164-54dca800-d045-11eb-8313-83fb3a3bf7d0.png) |

Fix default locale to FR

---

assets/scss/components/_alert.scss
content/blog/dev/manalize-virtualiser-son-environnement-de-developpement.md
content/blog/dev/migrer-mots-de-passe-utilisateur-autre-methode-encodage-symfony.md
templates/blog/article.html.twig

https://elao.github.io/elao_/pr/360/blog/dev/manalize-virtualiser-son-environnement-de-developpement/
et
https://elao.github.io/elao_/pr/360/blog/dev/migrer-mots-de-passe-utilisateur-autre-methode-encodage-symfony/

[Blog] Mark pwd migration article as outdated

---

content/blog/dev/les-attributs-php-8-dans-symfony.md

Hello,
Merci pour l'article, voici une PR qui corrige quelques typos mineures.

fix: add missing right square brackets

---

config/services.yaml
content/blog/elao/trame-itw.md

Comme discuté [ici](https://elao.slack.com/archives/C0156E6ACKF/p1622540388004100), l'idée étant de proposer une interview des membres de l'équipe à l'occasion de leur anniversaire d'embauche, en reprenant cette trame pour chaque personne.

Trame d'interview

---

assets/scss/components/_elaomojis.scss
config/services.yaml
package-lock.json
src/Emoji/ElaomojiParser.php
src/Stenope/Processor/ElaomojisProcessor.php

Parse les code elaomoji dans les articles

elaomojis processor

---

templates/footer.html.twig

🚨🚨🚨 WAIT
Merge when ready to tweet 🌝

Elaomojis link in footer

---

assets/js/feature/SocialPostGenerator.js
assets/scss/components/_social-post.scss
templates/site/social.html.twig

Introduce formats

---

content/blog/infra/utiliser-supervisor-pour-controler-ses-services-applicatifs.md

Fixes #394 
https://elao.github.io/elao_/pr/395/blog/infra/utiliser-supervisor-pour-controler-ses-services-applicatifs/

[Blog] Fix img inside html

---

assets/scss/components/_footer.scss

Fix https://github.com/Elao/elao_/issues/390

Fix footer alignement

---

content/blog/elao/nuit-du-hack-XV.md
templates/blog/article.html.twig

https://elao.github.io/elao_/pr/404/blog/elao/nuit-du-hack-XV

Nuit du hack XV fix content

---

assets/scss/components/_nav-mobile.scss
assets/scss/components/_nav.scss
templates/base.html.twig

Active menu styling

---

assets/scss/components/_article-info.scss

Fix https://github.com/Elao/elao_/issues/412

Fixed width

---

assets/scss/components/_tile.scss

Fix https://github.com/Elao/elao_/issues/426

“Fixed case study tiles for responsive layout”

---

assets/scss/components/prospect-contact.scss
assets/scss/pages/page-innovation-workshop.scss
templates/partials/footer.html.twig
templates/site/innovation-workshop.html.twig

https://elao.github.io/elao_/pr/428/atelier-innovation/

Mailjet widget

---

src/Controller/SiteController.php
templates/site/innovation-workshop.html.twig

Innovation workshop SEO optim

---

templates/blog/article.html.twig
templates/blog/index.html.twig

This PR fixes the issue with the width of the page for the blog index

Fix blog pages width 

---

assets/scss/components/_admonition.scss
assets/scss/components/_article-content.scss
content/blog/dev/api-design-elao-team-interview.md
content/blog/styleguide/example.md

this commit gives styling propositions to #152 
**Option 1 :** 
**Option 2:** 
**Option 3 :** 
**Option 4 :** _(my personal favorite, simple & elegant)_

Standardize admonitions

---

content/term/authentification-double-facteurs-2FA.md

https://elao.github.io/elao_/pr/433/glossaire/authentification-double-facteurs-2FA/

Glossaire : page sur la double authentification

---

assets/scss/pages/_page-job-posting.scss
content/job/job-responsable-operations-2022.md
templates/job/show.html.twig

Premier jet de l'offre d'emploi pour mon remplaçant. 
Le lien pour l'aperçu : https://elao.github.io/elao_/pr/445/recrutement/job-responsable-operations-2022/

Job offer - "Responsable des opérations"

---

templates/blog/article.html.twig
templates/blog/index.html.twig

Add rss link on the blog

---

content/job/office-manager-2022.md

https://elao.github.io/elao_/pr/459/recrutement/office-manager-2022/

[Jobs] - Annonce office manager

---

content/job/job-concepteur-developpeur-web-lyon-2022.md

https://elao.github.io/elao_/pr/461/recrutement/job-concepteur-developpeur-web-lyon-2022/

[Jobs] - Concepteur / Developpeur

---

assets/images/technos/default.svg
content/case-study/cirano.md
content/case-study/mjc.md
content/term/elasticsearch.md
content/term/payment.md
templates/glossary/term_list.html.twig

Add links to technos pages

---

content/term/stenope.md
package-lock.json

Ajout d'une page de glossaire concernant Stenope
Preview: https://elao.github.io/elao_/pr/480/glossaire/stenope/

[Glossary] Add a Stenope page

---

content/member/qbrouillet.yaml

Preview: https://elao.github.io/elao_/pr/478/la-tribu/qbrouillet/

Add Quentin as team member

---

templates/base.html.twig
templates/blog/article.html.twig
templates/case_study/index.html.twig
templates/case_study/show.html.twig
templates/site/contact.html.twig
templates/site/elaomojis.html.twig
templates/site/home.html.twig
templates/site/methodology.html.twig
templates/site/services.html.twig
templates/site/values.html.twig
templates/team/index.html.twig

Idem que coté Rix, on remonte sur `base` et on ajoute l'absolute path coté tag des médias à destination des RS.

[Global] - Uniformize social network media tags

---

assets/scss/components/_member.scss
templates/team/member.html.twig
translations/messages+intl-icu.fr.yaml

| - |- | - |
| - | - | - |
|![SCR-20220920-hir](https://user-images.githubusercontent.com/2211145/191236787-5d058647-7e8f-426b-853d-333333cd9642.png)|![SCR-20220920-hjd](https://user-images.githubusercontent.com/2211145/191236794-f4168a49-d3ca-4b71-86ec-8d63483452c0.png)|![SCR-20220920-hky](https://user-images.githubusercontent.com/2211145/191237169-fa740c34-6430-4809-a28b-83e4240fd94f.png)|

[Members] Change seniority label for < 1 month

---

.eslintrc.json
package-lock.json
package.json
webpack.config.js

https://github.com/symfony/webpack-encore/releases/tag/v4.0.0

Upgrade to Webpack Encore 4

---

composer.lock
config/packages/stenope.yaml
config/services.yaml
package-lock.json
src/Stenope/Processor/HtmlAnchorProcessor.php

See https://github.com/StenopePHP/Stenope/pull/169

[Stenope] Use new stenope processors config

---

content/job/job-facilitation-projets.md
templates/job/index.html.twig
templates/job/show.html.twig

Preview: https://elao.github.io/elao_/pr/508/recrutement/job-facilitation-projets/

Création de l'annonce pour le poste de facilitation projet

---

content/blog/styleguide/example.md

Close [Issue 68](https://github.com/Elao/interne/issues/68)
Précisions sur le sujet de l'écriture inclusive dans le guidestyle du blog, à savoir:
- liberté de l'auteur d'un article de l'utiliser ou non
- précision sur les solutions suggérées par ordre de préférence sur le blog

[BLOG] Clarifications for the use of inclusive writing

---

content/case-study/musique-music.md
content/case-study/tribu.md

Close Issue **_[Passage sur BC pour ajout citation #79](https://github.com/Elao/interne/issues/79)_**

[Content] Add quotes to business cases

---

assets/scss/base/_layout.scss
assets/scss/base/_variables.scss
assets/scss/generic/_a.scss
assets/scss/generic/_code.scss

✅ Smaller font size
✅ More contrast
✅ Bonus : change links colors from panic-why-is-the-link-red 🚨 to more-standard-blue
Fix https://github.com/Elao/interne/issues/108

💄 Improve code readability

---

content/member/eflahaut.yaml

Welcome @EmmFlt 😄 
https://elao.github.io/elao_/pr/545/la-tribu/eflahaut/

[Members] Add Emmmanuelle page tribu

---

assets/scss/components/_banner-home.scss
assets/scss/components/_brick-team.scss
assets/scss/components/_btn.scss
assets/scss/components/_team.scss
config/packages/glide.yaml
config/packages/twig.yaml
content/member/_sample.yaml
content/member/bleveque.yml
content/member/ccastillo.yaml
content/member/eflahaut.yaml
content/member/elao.yaml
content/member/equentin.yaml
content/member/llapeyre.yaml
content/member/slabbe.yaml
content/member/xavierr.yaml
content/member/xgorse.yml
content/member/yheitz.yaml
src/Controller/LegacyTeamController.php
src/Controller/TeamController.php
src/Model/Member.php
templates/site/home.html.twig
templates/team/index.html.twig
templates/team/member.html.twig

✅ Add a link to the job offers on the team page
✅ Change all occurrences of `tribe` and `tribu` to `team` or `magic team`
Preview : 👉 https://elao.github.io/elao_/pr/543/la-tribu 👈
fix https://github.com/Elao/interne/issues/107

Replace tribe to team & minor related tweaks

---

public/robots.txt

[SEO] Add robots.txt

---

assets/scss/components/_brick.scss

| Before | After |
| - | - |
| ![Capture d’écran 2023-11-09 à 14 34 51](https://github.com/Elao/elao_/assets/25897625/e4be17e2-e4d7-410e-9d8e-3d5ec0d711b6) | ![Capture d’écran 2023-11-09 à 14 33 45](https://github.com/Elao/elao_/assets/25897625/0375315f-f412-46f3-b5dc-6dc11933d876) |

Fix color in contact blocks

---

Makefile
assets/scss/components/_article-author.scss
assets/scss/components/_article-filter.scss
assets/scss/components/_article-list.scss
assets/scss/style.scss
config/packages/twig.yaml
src/Controller/BlogController.php
templates/base.html.twig
templates/blog/article.html.twig
templates/blog/articlesFromPath.html.twig
templates/blog/index.html.twig
templates/team/member.html.twig

> [!Note]
> Preview: https://elao.github.io/elao_/pr/586/blog/dev/
---
Following https://elao.slack.com/archives/C0156E6ACKF/p1700124956211069
```shell
ROUTER_DEFAULT_URI=http://localhost:8001/elao_ make test SHELL_VERBOSITY=3
```
- Retravailler l'intégration de la page par rapport aux maquettes prévues pour ces pages ?
- Revoir où placer ces liens ➜ actuellement, je les ait inclus dans les breadcrumb articles :

[Blog] List articles from a same path

---

templates/site/services/ia.html.twig

Part of https://github.com/Elao/amabla/issues/228
Preview (dans quelques minutes) ➜ https://elao.github.io/elao_/pr/596/nos-services/ia

[Services][IA] Replace contact link by Amabla landing page link

---

assets/scss/pages/_page-methodology.scss
templates/partials/ia-brief.html.twig
templates/site/approach/methodology.html.twig
templates/site/home.html.twig
templates/site/services/consulting.html.twig
templates/site/services/hosting.html.twig
templates/site/services/ia.html.twig
templates/site/services/services.html.twig
templates/site/values.html.twig

Closes https://github.com/Elao/interne/issues/230

[CONTENT] Add glossary links

---

content/job/job-concepteur-developpeur-front-lyon-2024.md
templates/job/show.html.twig

Preview: https://elao.github.io/elao_/pr/622/recrutement/job-concepteur-developpeur-front-lyon-2024/

[JOB] dev front

---

content/term/ui-ux.md
templates/site/approach/collaboration.html.twig
templates/site/approach/methodology.html.twig
templates/site/legal.html.twig
templates/site/privacy.html.twig

Hi 👋 ,
After reading some pages of your websites, I've found some typos.
Kind Regards,

chore: fix some typos
