Elao/elao_

- .github/workflows/clean_pr_preview.yaml
> [Github] Attempt to auto-clean a PR deployment on merge/close

- .manala/docker-compose.yaml
- Makefile
- README.md
- assets/js/app.js
- package-lock.json
- package.json
- templates/base.html.twig
- webpack.config.js
Utiliser `make dev` en lieu et place de `make watch` pour bénéficier du reload des assets en temps réel sans recharger la page.
Pour ceux utilisant Docker, il faudra éventuellement faire un `make clean up` pour reload les containers.
En complément, petite technique utilisé sur Shiningame: au changement d'un contenu Twig on force le refresh automatique de la page dans le navigateur.
Aussi, en utilisant une install locale au lieu de Docker (meilleures perfs), un `make start` démarre à la fois le serveur Symfony et Webpack avec le hot reloading.
> Webpack HMR

- content/blog/dev/donnees-structurees-offre-emploi.md
- content/blog/styleguide/example.md
- src/Model/Article.php
- templates/blog/article.html.twig
Suite à https://github.com/StenopePHP/Stenope/pull/101, on a maintenant une date de dernière modification cohérente disponible par défaut, se basant sur la date de dernier commit pour ce fichier.
Evidemment, pour les anciens articles réimportés dans le nouveau site, cette date serait incohérente. Il faut donc conserver le `lastModified: ~` explicite sur ceux-ci afin de désactiver la date de dernière modification.
Par contre, se pose la question sur le comportement que l'on souhaite par défaut pour les nouveaux articles ? A savoir:
1. `lastModified: ~` ➜ Date dernière modif désactivée, jusqu'à ce qu'on remplace explicitement par une date (ex: `lastModified: '2021-06-18'`) lors d'une mise à jour suffisamment importante de l'article. 
**Inconvénient** principal: il faut y penser.
1. Absence …
> [Blog] Rework last modified on articles

- .github/workflows/build_pr.yaml
Confusant de temps en temps, on garde le skip si la PR est en draft, mais si on utilise le label WIP pour simplement indiquer des changements en cours ou à venir suite à une 1ère step, on permet la preview.
> Allow WIP PRs to be deployed

- assets/scss/style.scss
A cause d'AOS (le module qu'on utilise pour les animations au scroll),
certaines règles CSS de la lib désactivent les interactions tant que
l'animation n'est pas faite.
Si le navigateur a le JS désactivé, AOS ne s'exécute donc pas, mais la
règle CSS est tjrs là et rend l'interaction impossible (liens, boutons, ...)
> Fix éléments non-interactifs si le JS est désactivé

- config/packages/stenope.yaml
- content/misc/elaomojis.yaml
- src/Controller/SiteController.php
- src/Model/Misc.php
- src/Serializer/Normalizer/StdClassDenormalizer.php
- templates/site/elaomojis.html.twig
- webpack.config.js
POC for https://github.com/StenopePHP/Stenope/issues/91#issuecomment-844415580
Such content pages allows any properties by relying on \stdClass specificities.
It just need creating once a class extending \stdClass. 
Then, any content, with various and different properties can be loaded with the content manager with its slug:
```php
$manager->getContent(Misc::class, 'elaomojis')
```
> [POC] Allow arbitrary "misc" pages

- .github/workflows/deploy.yaml
[Sondage](https://elao.slack.com/archives/CQ6L47QUB/p1625568686024200) par rapport à ça. Mais étant donné que plusieurs se font avoir / posent la question, et qu'au contraire personne ne semble lever de contre-indication à le faire, autant deploy le site en production automatiquement suite à un merge / commit sur `master`.
Reste la question de la publication des articles (cf sondage) et au moins garder en tête que tout merge sur master == dispo immédiate pour l'instant.
> [CI] Auto deploy on master push / merge PR to master

- content/blog/dev/les-attributs-php-8-dans-symfony.md
- content/blog/elao/anne-laure-developpeuse-web-chez-elao-depuis-3-ans.md
- content/blog/elao/trame-itw.md
- src/Command/GenerateArticleCommand.php
https://www.elao.com/blog/dev/les-attributs-php-8-dans-symfony apparaît actuellement avec une date de modification correspondant au dernier commit. Or dans #359 on était parti sur le fait de demander explicitement à mettre à jour la date lors d'un changement important uniquement afin d'éviter qu'elle change à chaque typo/refacto des métas articles.
Pour ça, il faut donc que les métas indiquent une date nulle explicitement afin qu'elle ne soit pas calculée automatiquement par le `LastModifiedProcessor`. Le `make article` a donc été mis à jour en conséquence.
> [Blog] Fix date de dernière modification

- content/blog/dev/les-attributs-php-8-dans-symfony.md
Hello l'équipe !
C'est ma première PR ici, n'hésitez pas à demander s'il manque des choses :)
J'ai trouvé des petites erreurs avec les arguments nommés sur l'[article](https://www.elao.com/blog/dev/les-attributs-php-8-dans-symfony) des attributs PHP8 dans Symfony. Elles ont été introduite ici: dc88ac9e52d1181d9257306565728d0bd6044239 avec la PR #368.
Merci pour votre blog !!
> Fix named arguments

- Makefile
- composer.json
- composer.lock
- src/Bridge/Glide/Bundle/DependencyInjection/GlideExtension.php
- src/Model/Job.php
Especially, fixes some of the PHP 8.1 deprecations (in Glide for instance, upgrading to v2)
- phpstan/phpstan (1.2.0 => 1.3.3)
- symfony/polyfill-php80 (v1.23.1 => v1.24.0)
- symfony/polyfill-mbstring (v1.23.1 => v1.24.0)
- symfony/polyfill-intl-normalizer (v1.23.0 => v1.24.0)
- symfony/polyfill-intl-grapheme (v1.23.1 => v1.24.0)
- symfony/string (v5.4.0 => v5.4.2)
- symfony/polyfill-php73 (v1.23.0 => v1.24.0)
- symfony/http-foundation (v5.4.1 => v5.4.2)
- symfony/var-dumper (v5.4.1 => v5.4.2)
- symfony/error-handler (v5.4.1 => v5.4.2)
- symfony/http-kernel (v5.4.1 => v5.4.2)
- symfony/dom-crawler (v5.4.0 => v5.4.2)
- symfony/polyfill-php81 (v1.23.0 => v1.24.0)
- symfony/dependency-injection (v5.4.1 => v5.4.2)
- symfony/css-selector (v5.4.0 => v5.4.2)
- elao/enum (2.x-dev ea76744 => …
> [Deps] Upgrade

- .github/workflows/deploy.yaml
- .github/workflows/deploy_pr_preview.yaml
- .github/workflows/deploy_staging.yaml
- .github/workflows/tests.yaml
Diff (le plus ancien run sans cache, le plus récent avec):
Sans cache:
Avec cache:
---
Each workflow cache is independent.
Cache will only grow ; each time a new image is added, Glide will spot the resized version is missing and generate one.
However, if the original image is deleted, it'll not be removed from cache.
One can alter the CACHE_VERSION secret to renew the whole cache at once.
Cache TTL is 7days (https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)
> [CI] Cache resized images to speed up deployments

- content/blog/dev/apollo-graphql-cache.md
"... dans le `case` de la première..." -> "... dans le `cache` de la première..."
> Typo: case to cache

- src/Model/Article.php
- templates/blog/article.html.twig
fix principalement la collection d'auteurs qui avait des clés, ce qui n'est pas attendu. 
Le reste c'est plus cosmétique/lisibilité du contenu généré pour debug
| Before | After |
| - | - |
|  ![SCR-20220921-dmv](https://user-images.githubusercontent.com/2211145/191446592-c51ddfea-8758-45c5-830d-5012642dc35e.png)  | ![SCR-20220921-dn3](https://user-images.githubusercontent.com/2211145/191446598-7e210e86-a5f6-456f-893c-a77ef6ee9f0e.png) |
> [Blog] Fix structured data

- content/blog/dev/stenope-skeleton.md
- src/Model/Article.php
- templates/blog/article.html.twig
Ajout des tags d'articles en tant que `keywords` dans les données structurées de [`NewsArticle`](https://schema.org/NewsArticle).
> **Note**: Les tags sont normalizés pour que les valeurs soient insensibles à la casse / espaces entre les mots.
> [Blog] Add keywords to structured data + add missing Symfony tag

- templates/partials/footer.html.twig
L'adresse d'elao dans le pied de page mentionne le `36 rue Jean BROQUIN` (au lieu du 34)
Aperçu : https://elao.github.io/elao_/pr/576/
> [Layout] Fix elao address in footer

- assets/scss/pages/_page-methodology.scss
- assets/scss/pages/_page-services.scss
- templates/partials/ia-brief.html.twig
- templates/site/home.html.twig
- templates/site/services/application.html.twig
- templates/site/services/consulting.html.twig
- templates/site/services/ia.html.twig
- templates/site/services/services.html.twig
Quelques fixs remontés par @evaelao sur https://github.com/Elao/elao_/pull/595
> [CONTENT] Fix previous PR 'add-glossary-links'

- content/member/elao.yaml
- src/Controller/BlogController.php
- src/Controller/SiteController.php
- src/Controller/TeamController.php
- src/Model/Member.php
- src/Stenope/Listener/BuildListener.php
- templates/blog/article.html.twig
- templates/blog/author.html.twig
- templates/blog/index.html.twig
- templates/case_study/show.html.twig
- templates/site/innovation-workshop.html.twig
Ex: "Team elao", "Amabla", …
Allows to have a link to list such authors' contents on the blog, but without having a team page entry: https://elao.github.io/elao_/pr/615/blog/auteur/elao/
> [Blog][Team] Added meta members

- kubernetes/charts/website/templates/ingress.yaml
Il manquait la redir elao.com -> www.elao.com
C'est l'ingress au niveau kube qui s'en charge. Pour ne pas embarquer blog.elao.com dans la redir, je lui fait un ingress dédié.
> Redirect website to www

- content/blog/dev/apollo-mock-data-local-resolvers.md
- src/Model/Article.php
- templates/blog/article.html.twig
- templates/blog/index.html.twig
- templates/glossary/index.html.twig
- templates/glossary/term.html.twig
- templates/macros.html.twig
- templates/site/home.html.twig
- templates/team/member.html.twig
It allows a more fine-grained control over the rendering of the same image in different context, per article,
and can even provide options per preset used.
For instance, I can control the resize of the `article_thumbnail.lg` preset to avoid cropping and filling spaces with white color:
| Before | After |
| - | - |
|![image](https://github.com/user-attachments/assets/4304a81f-888c-447b-8866-ee1007d0dd79)|<video src="https://github.com/user-attachments/assets/4258d32a-a6e6-4c86-9895-697fddacdf49"></video>|
> [Blog] Allow to provide resize options for thumbnails / banner

- .manala.yaml
- .manala/docker/compose.yaml
- Makefile
- README.md
so we have something more close to regular projects and eliminates some difference between the local setup (for PHP devs) and the Docker ones (for more punctual needs / non PHP-devs)
```shell
make setup
```
will now up the container and install deps + build assets.
```shell
make serve
```
from inside the container, will only start the required webpack dev-server for development purposes (CSS/JS).
> [Stack] Streamline Docker setup with local

- templates/blog/article.html.twig
- templates/blog/articlesFromPath.html.twig
Devrait solutionner le soucis d'articles de blog dans un sous-répertoire (plus profond que le 1er niveau).
C'est l'alternative la plus complexe: chaque sous niveau devient une entrée du breadcrumb spécifique, et une telle arborescence créée alors une page de référence supplémentaire.
Par ex, pour : https://www.elao.com/blog/elao/alternants/accompagnement-alternants-episode-1
une page:
- `/blog/elao` (existante)
- une nouvelle page `/blog/elao/alternants` ne listant que les article du sous-répertoire `elao/alternants` apparaît.
Résultant en : `Accueil / Blog Elao / Alternants / [Épisode 1/5] Panique ! Nos alternant·e·s ont été lâché·e·s en eau libre`
A voir si c'est ce que l'on souhaite, ou si l'on préfère opter pour ne conserver qu'un seul niveau.
Dans ce dernier cas, le fil d'ariane …
> [Blog] Fix breadcrumbs for nested subdirectories
